# Generated by Django 2.2.17 on 2021-02-05 03:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20210204_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
