# Generated by Django 2.2.17 on 2021-02-05 03:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20210204_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
