# Generated by Django 2.2.17 on 2021-02-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20210204_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='uuid',
        ),
    ]
