# Generated by Django 2.2.17 on 2021-02-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_remove_bookinstance_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='uuid',
            field=models.UUIDField(default='d67641ab-cdfb-4992-841e-20b9a756fc36', help_text='Unique ID for this particular book across whole library'),
        ),
    ]
