# Generated by Django 2.2.17 on 2021-02-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_bookinstance_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='uuid',
            field=models.CharField(default='00177bab-ad3e-48d9-84e0-b10803c49897', max_length=40),
        ),
    ]
