# Generated by Django 2.2.17 on 2021-02-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20210204_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='uuid',
            field=models.CharField(default=5, max_length=40),
        ),
    ]
