# Generated by Django 2.2.17 on 2021-02-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20210204_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='uuid',
        ),
    ]
