# Generated by Django 2.2.17 on 2021-02-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_remove_bookinstance_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('librarian', 'librarian'),)},
        ),
    ]
